name: mvp_platform
description: Mobile Platform Bootstrap

flutter_launcher_name:
  name: "Госуслуги"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  equatable: ^1.2.0
  flutter_svg: ^0.17.4
  fluttertoast: ^4.0.1
  http: ^0.12.1
  intl: ^0.16.1
  provider: ^4.1.2
  shared_preferences: 0.5.7+3
  simple_gesture_detector: ^0.1.4
#  table_calendar: ^2.2.3
  tuple: ^1.0.3
  yandex_mapkit: ^0.3.8


dev_dependencies:
  build_runner: 1.9.0
  flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: "^0.7.5"
  dataclass_generator: "0.3.0+1"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon_ios.png"
  image_path_android: "assets/launcher/icon_android.png"

flutter:
  uses-material-design: true
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
  assets:
    - assets/images/gos-main-logo.png
    - assets/images/doctors/doctor.jpg
    - assets/images/doctors/09371194987.jpg
    - assets/images/doctors/15763827807.jpg
    - assets/images/doctors/doctor-3.jpg
    - assets/icons/phonedoscope.png
    - assets/icons/notificationIcon.png
    - assets/icons/backdeletebackspace.png
    - assets/map/1.png
    - assets/map/2.png
    - assets/map/3.png
    - assets/map/4.png
    - assets/map/5.png
    - assets/map/6.png
    - assets/svg/icons8-search.svg
    - assets/svg/backspace-arrow.svg
    - assets/svg/fingerprint.svg
    - assets/svg/avatar.svg
    - assets/json/createcontrolcard.json
    - assets/cert/rootCA.crt
    - assets/cert/rootCA.key
    - assets/cert/client.example.crt
    - assets/cert/client.example.key
    - assets/cert/ingress.foms_correct.crt
    - assets/cert/ingress.foms_correct.key
    - assets/cert/chain.crt
    - assets/med_organization/2.png
    - assets/med_organization/3.png
    - assets/med_organization/4.png